# This file is part of the Sylius sandbox Sylius\Sandbox.
# (c) Paweł Jędrzejewski

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: database.yml }

framework:
    default_locale: %sylius.locale%
    form: ~
    charset:       UTF-8
    secret: %sylius.secret%
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing/base.yml" }
    validation:    { enabled: true, enable_annotations: true }
    translator:    { fallback: %sylius.locale% }
    templating:    { engines: ['twig', 'php'] }
    session:
        name: SYLIUS_SANDBOX_SESSION
        lifetime: 72000
        auto_start:     true

twig:
    form:
        resources:
            - 'SandboxCoreBundle::forms.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:      %kernel.root_dir%/../public

swiftmailer:
    disable_delivery: true
    transport: %sylius.mailer.transport%
    host:      %sylius.mailer.host%
    username:  %sylius.mailer.user%
    password:  %sylius.mailer.password%

stof_doctrine_extensions:
    default_locale: %sylius.locale%
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true

avalanche_imagine:
    source_root:  %kernel.root_dir%/../public
    web_root: %kernel.root_dir%/../public
    cache_prefix: media/cache
    filters:
        frontend_medium:
            type: thumbnail
            options: { size: [220, 180], mode: outbound }
        backend_mini:
            type: thumbnail
            options: { size: [90, 60], mode: outbound }

sylius_assortment:
    driver: doctrine/orm
    api: true
    classes:
        model:
            product: Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Product
            variant: Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Variant\Variant
            property: Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Property\Property
            product_property: Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Property\ProductProperty
            prototype: Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Prototype\Prototype
            option: Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Option\Option
            option_value: Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Option\OptionValue
        form:
            type:
                product: Sylius\Sandbox\Bundle\AssortmentBundle\Form\Type\ProductType
                variant: Sylius\Sandbox\Bundle\AssortmentBundle\Form\Type\VariantType

sylius_categorizer:
    driver: doctrine/orm
    catalogs:
        assortment:
            property: "products"
            model: Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Category
            form: sylius_sandbox_assortment_category
            templates:
                backend: SandboxAssortmentBundle:Backend/Category:%s.html.twig
                frontend: SandboxAssortmentBundle:Frontend/Category:%s.html.twig
        blog:
            property: "posts"
            model: Sylius\Sandbox\Bundle\BloggerBundle\Entity\Category
            templates:
                backend: SandboxBloggerBundle:Backend/Category:%s.html.twig
                frontend: SandboxBloggerBundle:Frontend/Category:%s.html.twig

sylius_cart:
    driver: doctrine/orm
    operator: sylius_sandbox_cart.operator
    resolver: sylius_sandbox_cart.resolver
    classes:
        model:
            cart: Sylius\Sandbox\Bundle\CartBundle\Entity\Cart
            item: Sylius\Sandbox\Bundle\CartBundle\Entity\Item
        manager:
            cart: Sylius\Sandbox\Bundle\CartBundle\Entity\CartManager
        form:
            type:
                item: Sylius\Sandbox\Bundle\CartBundle\Form\Type\ItemType

sylius_blogger:
    driver: doctrine/orm
    classes:
        model:
            post: Sylius\Sandbox\Bundle\BloggerBundle\Entity\Post
        form:
            type:
                post: Sylius\Sandbox\Bundle\BloggerBundle\Form\Type\PostType

sylius_sales:
    driver: doctrine/orm
    classes:
        model:
            order: Sylius\Sandbox\Bundle\SalesBundle\Entity\Order
            item: Sylius\Sandbox\Bundle\SalesBundle\Entity\Item
            status: Sylius\Bundle\SalesBundle\Entity\Status
        form:
            type:
                order: Sylius\Sandbox\Bundle\SalesBundle\Form\Type\OrderType
                item: Sylius\Sandbox\Bundle\SalesBundle\Form\Type\ItemType

sylius_addressing:
    driver: doctrine/orm
    classes:
        model:
            address: Sylius\Sandbox\Bundle\AddressingBundle\Entity\Address
        form:
            type:
                address: Sylius\Bundle\AddressingBundle\Form\Type\CommonAddressType

sylius_inventory:
    driver: doctrine/orm
    classes:
        model:
            iu: Sylius\Bundle\InventoryBundle\Entity\InventoryUnit
