# This file is part of the Sylius sandbox Sylius\Bundle.
# (c) Paweł Jędrzejewski

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: database.yml }

framework:
    default_locale: %sylius.locale%
    form: ~
    secret: %sylius.secret%
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing/base.yml" }
    validation:    { enabled: true, enable_annotations: true }
    translator:    { fallback: %sylius.locale% }
    templating:    { engines: ['twig', 'php'] }
    session:
        name: SYLIUS_SANDBOX_SESSION
        lifetime: 72000

twig:
    form:
        resources:
            - 'SyliusSandboxBundle::forms.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from:      %kernel.root_dir%/../public

swiftmailer:
    disable_delivery: %kernel.debug%
    transport: %sylius.mailer.transport%
    host:      %sylius.mailer.host%
    username:  %sylius.mailer.user%
    password:  %sylius.mailer.password%

stof_doctrine_extensions:
    default_locale: %sylius.locale%
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true

avalanche_imagine:
    source_root:  %kernel.root_dir%/../public
    web_root: %kernel.root_dir%/../public
    cache_prefix: media/cache
    filters:
        frontend_medium:
            type: thumbnail
            options: { size: [220, 180], mode: outbound }
        frontend_box:
            type: thumbnail
            options: { size: [130, 75], mode: outbound }
        backend_mini:
            type: thumbnail
            options: { size: [90, 60], mode: outbound }
        backend_medium:
            type: thumbnail
            options: { size: [250, 150], mode: outbound }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Sylius\Bundle\SandboxBundle\Entity\User

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Sylius\Bundle\SandboxBundle\Entity\Comment
            thread: Sylius\Bundle\SandboxBundle\Entity\Thread
    acl: true
    service:
        acl:
            thread: fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote: fos_comment.acl.vote.roles
    acl_roles:
        comment:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_SYLIUS_ADMIN
            delete: ROLE_SYLIUS_ADMIN
        thread:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_SYLIUS_ADMIN
            delete: ROLE_SYLIUS_ADMIN
        vote:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_SYLIUS_ADMIN
            delete: ROLE_SYLIUS_ADMIN

mopa_bootstrap:
    navbar: ~

sylius_assortment:
    driver: doctrine/orm
    classes:
        model:
            product: Sylius\Bundle\SandboxBundle\Entity\Product
            variant: Sylius\Bundle\SandboxBundle\Entity\Variant\Variant
            property: Sylius\Bundle\SandboxBundle\Entity\Property\Property
            product_property: Sylius\Bundle\SandboxBundle\Entity\Property\ProductProperty
            prototype: Sylius\Bundle\SandboxBundle\Entity\Prototype\Prototype
            option: Sylius\Bundle\SandboxBundle\Entity\Option\Option
            option_value: Sylius\Bundle\SandboxBundle\Entity\Option\OptionValue
        controller:
            product: Sylius\Bundle\SandboxBundle\Controller\ProductController
        repository:
            product: Sylius\Bundle\SandboxBundle\Repository\ProductRepository
        form:
            type:
                product: Sylius\Bundle\SandboxBundle\Form\Type\ProductType
                variant: Sylius\Bundle\SandboxBundle\Form\Type\VariantType

sylius_categorizer:
    driver: doctrine/orm
    catalogs:
        blog:
            property: "posts"
            model: Sylius\Bundle\SandboxBundle\Entity\PostCategory
            templates:
                backend: SyliusSandboxBundle:Backend/PostCategory:%s.html.twig
                frontend: SyliusSandboxBundle:Frontend/PostCategory:%s.html.twig

sylius_cart:
    driver: doctrine/orm
    resolver: sylius_sandbox_cart.resolver
    classes:
        cart:
            repository: Sylius\Bundle\SandboxBundle\Repository\CartRepository
        item:
            model: Sylius\Bundle\SandboxBundle\Entity\CartItem
            form: Sylius\Bundle\SandboxBundle\Form\Type\CartItemType

sylius_blogger:
    driver: doctrine/orm
    classes:
        post:
            model: Sylius\Bundle\SandboxBundle\Entity\Post
            form: Sylius\Bundle\SandboxBundle\Form\Type\PostType

sylius_sales:
    driver: doctrine/orm
    builder: sylius_sandbox.builder.order
    classes:
        order:
            model: Sylius\Bundle\SandboxBundle\Entity\Order
            form: Sylius\Bundle\SandboxBundle\Form\Type\OrderType
        item:
            model: Sylius\Bundle\SandboxBundle\Entity\OrderItem
            form: Sylius\Bundle\SandboxBundle\Form\Type\OrderItemType

sylius_addressing:
    driver: doctrine/orm

sylius_inventory:
    driver: doctrine/orm
    backorders: false
    classes:
        model:
            iu: Sylius\Bundle\SandboxBundle\Entity\InventoryUnit

sylius_taxonomies:
    driver: doctrine/orm
    classes:
        taxonomy:
            model: Sylius\Bundle\SandboxBundle\Entity\Taxonomy
        taxon:
            model: Sylius\Bundle\SandboxBundle\Entity\Taxon

sylius_resource:
    resources:
        sylius_user.user:
            driver: doctrine/orm
            classes:
                model: Sylius\Bundle\SandboxBundle\Entity\User
