# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_core:
    resource: @SandboxCoreBundle/Resources/config/routing/base.yml

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart

sylius_categorizer_category:
    resource: @SyliusCategorizerBundle/Resources/config/routing/backend/category.yml
    prefix: /administration

sylius_categorizer_backend_category:
    resource: @SyliusCategorizerBundle/Resources/config/routing/frontend/category.yml

sylius_flow:
    resource: @SyliusFlowBundle/Resources/config/routing.yml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api

_imagine:
    resource: .
    type: imagine
