# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_core:
    resource: @SandboxCoreBundle/Resources/config/routing/base.yml

sylius_sandbox_assortment:
    resource: @SandboxAssortmentBundle/Resources/config/routing.yml

sylius_sandbox_sales:
    resource: @SandboxSalesBundle/Resources/config/routing.yml

sylius_sandbox_user:
    resource: @SandboxUserBundle/Resources/config/routing.yml

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart

sylius_categorizer_category:
    resource: @SyliusCategorizerBundle/Resources/config/routing/backend/category.yml
    prefix: /administration

sylius_categorizer_backend_category:
    resource: @SyliusCategorizerBundle/Resources/config/routing/frontend/category.yml

sylius_flow:
    resource: @SyliusFlowBundle/Resources/config/routing.yml

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api

_imagine:
    resource: .
    type: imagine
