# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_core:
    resource: @SandboxCoreBundle/Resources/config/routing.yml

sylius_sandbox_assortment:
    resource: @SandboxAssortmentBundle/Resources/config/routing.yml

sylius_sandbox_cart:
    resource: @SandboxCartBundle/Resources/config/routing.yml

sylius_sandbox_blogger:
    resource: @SandboxBloggerBundle/Resources/config/routing.yml

sylius_sandbox_sales:
    resource: @SandboxSalesBundle/Resources/config/routing.yml

sylius_sandbox_addressing:
    resource: @SandboxAddressingBundle/Resources/config/routing.yml

sylius_categorizer_category:
    resource: @SyliusCategorizerBundle/Resources/config/routing/backend/category.yml
    prefix: /administration

sylius_categorizer_backend_category:
    resource: @SyliusCategorizerBundle/Resources/config/routing/frontend/category.yml

_imagine:
    resource: .
    type: imagine
