# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_core_frontend:
    pattern: /
    defaults: { _controller: sylius_sandbox_core.controller.frontend.main:indexAction }

sylius_sandbox_checkout_start:
    pattern: /checkout
    defaults: { _controller: sylius_flow.controller.process:startAction, scenarioAlias: 'sylius_sandbox_checkout' }

sylius_sandbox_checkout_display:
    pattern: /checkout/{stepName}
    defaults: { _controller: sylius_flow.controller.process:displayAction, scenarioAlias: 'sylius_sandbox_checkout' }

sylius_sandbox_checkout_forward:
    pattern: /checkout/{stepName}/forward
    defaults: { _controller: sylius_flow.controller.process:forwardAction, scenarioAlias: 'sylius_sandbox_checkout' }
