# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

doctrine:
    dbal:
        driver:   %database.driver%
        host:     %database.host%
        port:     %database.port%
        dbname:   %database.name%
        user:     %database.user%
        password: %database.password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
