# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_core_backend:
    pattern: /
    defaults: { _controller: sylius_sandbox_core.controller.backend.main:indexAction }

sylius_sandbox_backend_address:
    prefix: /addresses
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/address.yml

sylius_sandbox_backend_country:
    prefix: /countries
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/country.yml

sylius_sandbox_backend_province:
    prefix: /countries/{countryId}/provinces
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/province.yml

sylius_sandbox_backend_zone:
    prefix: /zones
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/zone.yml

sylius_sandbox_backend_zone_member:
    prefix: /zones/{zoneId}/members
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/zone_member.yml

sylius_sandbox_backend_order:
    prefix: /orders
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/order.yml

sylius_sandbox_backend_product:
    prefix: /products
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/product.yml

sylius_sandbox_backend_option:
    prefix: /option
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/option.yml

sylius_sandbox_backend_variant:
    prefix: /products/{productId}/variants
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/variant.yml

sylius_sandbox_backend_property:
    prefix: /properties
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/property.yml

sylius_sandbox_backend_prototype:
    prefix: /prototypes
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/prototype.yml

sylius_sandbox_backend_post:
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/post.yml
    prefix: /posts

sylius_sandbox_backend_taxonomy:
    prefix: /taxonomies
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/taxonomy.yml

sylius_sandbox_backend_taxon:
    prefix: /taxonomies/{taxonomyId}/taxons
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/taxon.yml

sylius_sandbox_backend_tax_category:
    prefix: /tax-categories
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/tax_category.yml

sylius_sandbox_backend_tax_rate:
    prefix: /tax-rates
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/tax_rate.yml

sylius_sandbox_backend_shipping_category:
    prefix: /shipping-categories
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/shipping_category.yml

sylius_sandbox_backend_shipping_method:
    prefix: /shipping-methods
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/shipping_method.yml

sylius_sandbox_backend_user:
    prefix: /users
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/user.yml

sylius_sandbox_backend_settings:
    prefix: /settings
    resource: @SyliusSandboxBundle/Resources/config/routing/backend/settings.yml
