# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_backend_country_list:
    pattern: /
    defaults:
        _controller: sylius.controller.country:indexAction
        _template: SyliusSandboxBundle:Backend/Country:list.html.twig
        _paginate: 50

sylius_sandbox_backend_country_create:
    pattern: /create
    defaults:
        _controller: sylius.controller.country:createAction
        _template: SyliusSandboxBundle:Backend/Country:create.html.twig
        _redirect: sylius_sandbox_backend_country_list

sylius_sandbox_backend_country_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius.controller.country:updateAction
        _template: SyliusSandboxBundle:Backend/Country:update.html.twig
        _redirect: sylius_sandbox_backend_country_list

sylius_sandbox_backend_country_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.country:deleteAction
        _redirect: sylius_sandbox_backend_country_list
