# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_backend_option_list:
    pattern: /
    defaults: 
        _controller: sylius_assortment.controller.option:getCollectionAction
        _sylius.resource:
            template: SyliusSandboxBundle:Backend/Option:list.html.twig

sylius_sandbox_backend_option_create:
    pattern: /create
    defaults: 
        _controller: sylius_assortment.controller.option:createAction
        _sylius.resource:
            template: SyliusSandboxBundle:Backend/Option:create.html.twig
            redirect: sylius_sandbox_backend_option_list

sylius_sandbox_backend_option_update:
    pattern: /{id}/update
    defaults: 
        _controller: sylius_assortment.controller.option:updateAction
        _sylius.resource:
            template: SyliusSandboxBundle:Backend/Option:update.html.twig
            redirect: sylius_sandbox_backend_option_list

sylius_sandbox_backend_option_delete:
    pattern: /{id}/delete
    defaults: 
        _controller: sylius_assortment.controller.option:deleteAction
        _sylius.resource:
            redirect: sylius_sandbox_backend_option_list
