# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_backend_property_list:
    pattern: /
    defaults:
        _controller: sylius_assortment.controller.property:indexAction
        _template: SyliusSandboxBundle:Backend/Property:list.html.twig
        _sortable: true
        _sorting:
            name: desc

sylius_sandbox_backend_property_create:
    pattern: /create
    defaults:
        _controller: sylius_assortment.controller.property:createAction
        _template: SyliusSandboxBundle:Backend/Property:create.html.twig
        _redirect: sylius_sandbox_backend_property_list

sylius_sandbox_backend_property_update:
    pattern: /update
    defaults:
        _controller: sylius_assortment.controller.property:updateAction
        _template: SyliusSandboxBundle:Backend/Property:update.html.twig
        _redirect: sylius_sandbox_backend_property_list

sylius_sandbox_backend_property_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_assortment.controller.property:deleteAction
        _redirect: sylius_sandbox_backend_property_list
