# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_backend_zone_member_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_addressing.controller.zone_member:deleteAction
        _redirect: sylius_sandbox_backend_zone_list
